#FROM nvidia/cuda:11.6.0-cudnn8-devel-ubuntu20.04
FROM nvidia/cudagl:11.3.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
	python3-opencv ca-certificates python3-dev git wget sudo ninja-build
RUN ln -sv /usr/bin/python3 /usr/bin/python

RUN wget https://bootstrap.pypa.io/get-pip.py && \
	python3 get-pip.py && \
	rm get-pip.py

RUN pip install tensorboard cmake onnx   # cmake from apt-get is too old
RUN pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip install 'git+https://github.com/facebookresearch/fvcore'

ENV FORCE_CUDA="1"

ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"

RUN pip install 'git+https://github.com/facebookresearch/detectron2'

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
	libjpeg-dev zlib1g-dev \
	libopenexr-dev \
	openexr \
	python3-dev \
	libglfw3-dev libglfw3 \
	libglew-dev \
	libassimp-dev \
	libnuma-dev \
	clang \
	## for bop cpp renderer
	curl \
	autoconf \
	libtool \
	## for uncertainty pnp
	libeigen3-dev \
	libgoogle-glog-dev \
	libsuitesparse-dev \
	libatlas-base-dev \
	## for nvdiffrast/egl
	cmake curl pkg-config \
	libgles2 \
	libgl1-mesa-dev \
	libegl1-mesa-dev \
	libgles2-mesa-dev \
	# (only available for Ubuntu >= 18.04)
	libglvnd0 \
	libgl1 \
	libglx0 \
	libegl1 \
	libglvnd-dev \
	libglew-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip install cython
RUN pip install plyfile
RUN pip install ujson  # make json loading in cocoapi_nvidia faster
RUN pip install pycocotools
RUN pip install cffi
RUN pip install ninja
RUN pip install black
RUN pip install docformatter
RUN pip install setproctitle
RUN pip install meshplex
RUN pip install OpenEXR
RUN pip install vispy>=0.6.4
RUN pip install yacs>=0.1.8
RUN pip install tabulate
RUN pip install pytest-runner
RUN pip install pytest
RUN pip install ipdb
RUN pip install tqdm
RUN pip install numba
RUN pip install mmcv
RUN pip install imagecorruptions
RUN pip install pyassimp==4.1.3  # 4.1.4 will cause egl_renderer SegmentFault
RUN pip install pypng
RUN pip install imgaug>=0.4.0
RUN pip install albumentations
RUN pip install transforms3d
# pyquaternion
RUN pip install torchvision
RUN pip install open3d
RUN pip install fvcore
RUN pip install tensorboardX
RUN pip install einops
RUN pip install pytorch3d
RUN pip install timm  # pytorch-image-models
RUN pip install glfw
RUN pip install imageio
RUN pip install imageio-ffmpeg
RUN pip install PyOpenGL  # >=3.1.5
RUN pip install PyOpenGL_accelerate
RUN pip install chardet

RUN pip install thop  # https://github.com/Lyken17/pytorch-OpCounter
RUN pip install loguru

RUN pip install pytorch-lightning==1.6.0  # tested for 1.6.0.dev0
RUN pip install fairscale
RUN pip install deepspeed

# verified versions
RUN pip install pyro-ppl==1.4.0 #for epro-pnp <1.8.1
RUN pip install onnx==1.8.1
RUN pip install onnxruntime==1.8.0
RUN pip install onnx-simplifier==0.3.5
RUN pip install glumpy


#RUN sh /gdrnpp_bop2022/scripts/compile_all.sh
RUN mkdir gdrnpp_bop2022
WORKDIR /gdrnpp_bop2022

